
CREATE TABLE IF NOT EXISTS aircraft_metadata (
    icao24 TEXT PRIMARY KEY,
    registration TEXT,
    manufacturericao TEXT,
    manufacturername TEXT,
    model TEXT,
    typecode TEXT,
    serialnumber TEXT,
    linenumber TEXT,
    aircrafttype TEXT,
    operator TEXT,
    operatorcallsign TEXT,
    operatoricao TEXT,
    operatoriata TEXT,
    owner TEXT,
    testreg TEXT,
    registered TEXT,
    reguntil TEXT,
    status TEXT,
    built TEXT,
    firstflightdate TEXT,
    seatconfiguration TEXT,
    engines TEXT,
    modes TEXT,
    adsb TEXT,
    acars TEXT,
    notes TEXT,
    category TEXT
);
